server:
  port: 8085

spring:
#  profiles:
#    active: prod
  application:
    name: USER-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/userservicedb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

#  mvc:
#    pathmatch:
#      matching-strategy: ANT_PATH_MATCHER
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    

  config:
    import: optional:configserver:http://localhost:8777

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8088/eureka
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health

  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      ratingHotelBreaker:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 6s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED

  retry:
    instances:
      ratingHotelRetry:
        maxAttempts: 3
        waitDuration: 5s

  ratelimiter:
    instances:
      ratingHotelRatelimiter:
        limitRefreshPeriod: 4s
        limitForPeriod: 2
        timeoutDuration: 2s
